routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/about', 'Frontend\AboutController@index')->name('about');
Route::get('/news', 'Frontend\NewsController@index')->name('news');
Route::get('/news/detail/{news}', 'Frontend\NewsController@show')->name('news.detail');
Route::get('/products', 'Frontend\ProductsController@index')->name('products');
Route::get('/products/detail/{product}', 'Frontend\ProductsController@show')->name('products.detail');
Route::get('/shop','Frontend\ShopController@index')->name('shop');

//cart route
Route::get('/add-to-cart/{id}', 'Frontend\CartController@getAddToCart')->name('product.addToCart');
Route::get('/cart', 'Frontend\CartController@index')->name('cart');
Route::patch('/cart/{id}', 'Frontend\CartController@updateCart')->name('cart.update');
Route::delete('/cart/{id}', 'Frontend\CartController@deleteCart')->name('cart.delete');

//order and payment route
Route::middleware(['auth'])->group(function(){
    Route::get('/order','Frontend\OrderController@index')->name('cart.order');
    Route::post('/order','Frontend\OrderController@order_confirm')->name('cart.order.confirm');
    
    Route::get('/payment','Frontend\PaymentController@index')->name('cart.payment');
    Route::post('/checkout','Frontend\PaymentController@checkout')->name('cart.checkout');

    Route::get('/orders','Frontend\User\OrdersController@index')->name('orders');
    Route::get('/order_detail/{id}','Frontend\User\OrdersController@getOrder')->name('order.detail');

    Route::get('/profile', 'Frontend\User\ProfileController@index')->name('profile');
    Route::post('/profile', 'Frontend\User\ProfileController@update')->name('profile.update');

    Route::get('/resetpassword', 'Frontend\User\ResetPasswordController@index')->name('resetpassword');
    Route::post('/resetpassword', 'Frontend\User\ResetPasswordController@update')->name('resetpassword.update');
});
Route::prefix('admin')->group(function () {
    Route::get('/', 'Auth\AdminController@showLoginForm')->name('admin.login');
    Route::post('/', 'Auth\AdminController@login')->name('admin.login');
    Route::post('/logout', 'Auth\AdminController@logout')->name('admin.logout');
});
Route::middleware(['auth:admin'])->group(function(){
    Route::get('/dashboard', 'Backend\DashBoardController@index')->name('dashboard');

    
    Route::prefix('backend')->group(function () {
        Route::group(['as' => 'backend.home.'], function() {
            Route::resource('/carousel', 'Backend\Home\CarouselController');
            Route::resource('/aboutdiv', 'Backend\Home\AboutDivController');
        });
    
        Route::group(['as' => 'backend.share.'], function() {
            Route::get('/shopinfo', 'Backend\Share\ShopInfoController@index')->name('shopinfo.index');
            Route::put('/shopinfo/{id}', 'Backend\Share\ShopInfoController@update')->name('shopinfo.update');
            Route::get('/footer', 'Backend\Share\FooterController@index')->name('footer.index');
            Route::put('/footer/{id}', 'Backend\Share\FooterController@update')->name('footer.update');
        });
    
        Route::group(['as' => 'backend.about.'], function() {
            Route::resource('/introdiv', 'Backend\About\IntroDivController');
            Route::resource('/historydiv', 'Backend\About\HistoryDivController');
        });
    
        Route::group(['as' => 'backend.news.'], function() {
            Route::resource('/newsdiv', 'Backend\News\NewsController');
        });
    
        Route::group(['as' => 'backend.products.'], function() {
            Route::resource('/menu', 'Backend\Products\MenuController');
            Route::resource('/product', 'Backend\Products\ProductController');
            Route::resource('/product-type', 'Backend\Products\ProductTypeController');
        });
    
        Route::group(['as' => 'backend.shop.'], function() {
            Route::resource('/shop-detail', 'Backend\Shop\ShopController');
        });

        Route::group(['as' => 'backend.user.'], function() {
            Route::resource('/orders', 'Backend\User\OrdersController');
            Route::get('/users', 'Backend\User\UsersController@index')->name('users.index');
        });
    });
    



});

Auth::routes();

app/Http/Controllers/Backend/About/HistoryDivController.php
<?php

namespace App\Http\Controllers\Backend\About;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\About\HistoryDiv;

class HistoryDivController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $historys = HistoryDiv::paginate(5);
        return view('backend.about.historydiv.index',compact('historys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'text' =>['required','string']
        ]);

        HistoryDiv::create([
            'title'=>$request->input('title'),
            'text'=>$request->input('text'),
        ]);

        return redirect()->route('backend.about.historydiv.index')
                         ->with('success', 'New history div post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $history = HistoryDiv::find($id);
        return view('backend.about.historydiv.edit',compact('history'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'text' =>['required','string']
        ]);
        $history = HistoryDiv::find($id);
        $history->title = $request->input('title');
        $history->text = $request->input('text');
        $history->save();
        
        return redirect()->route('backend.about.historydiv.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $history = HistoryDiv::find($id);
        $history->delete();
        return redirect()->route('backend.about.historydiv.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/About/IntroDivController.php
<?php

namespace App\Http\Controllers\Backend\About;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\About\IntroDiv;
class IntroDivController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $introdivs = IntroDiv::paginate(5);
        return view('backend.about.introdiv.index',compact('introdivs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.about.introdiv.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'image'=>['required','image'],
            'text' =>['required','string']
        ],$messages = [

        ]);
     
        //if do not have introdiv directory, add it
        if (!file_exists('uploads/introdiv')) {
            mkdir('uploads/introdiv', 0755, true);
        }
        //set image path ,name and move it to local directory 
        $file = $request->file('image');

        $path = public_path() . '/uploads/introdiv/';
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $file->move($path, $fileName);

        IntroDiv::create([
            'title' =>  $request->input('title'),
            'image'=>$fileName,
            'text' => $request->input('text')
        ]);
        return redirect()->route('backend.about.introdiv.index')
                         ->with('success', 'New intro div post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $introdiv = IntroDiv::find($id);
        return view('backend.about.introdiv.detail',compact('introdiv'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $introdiv = IntroDiv::find($id);
        return view('backend.about.introdiv.edit',compact('introdiv'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'image'=>['image'],
            'text' =>['string']
        ],$messages = [
        ]);
        $introdiv = IntroDiv::find($id);
        
        if ($request->file('image')) {
            //remove original file
            @unlink('uploads/introdiv/' . $introdiv->image);

            //set image path ,name and move it to local directory
            $file = $request->file('image');
            $path = public_path() . '\uploads\introdiv\\';
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move($path, $fileName);

            $introdiv->image =  $fileName;
        }
        $introdiv->title = $request->get('title');
        $introdiv->text = $request->get('text');
        $introdiv->save();
        
        return redirect()->route('backend.about.introdiv.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $introdiv = IntroDiv::find($id);
        //remove img
        @unlink('uploads/introdiv/' . $introdiv->image);
        $introdiv->delete();
        return redirect()->route('backend.about.introdiv.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/DashBoardController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Models\Orders;
use App\Models\Earnings;
use App\Models\ProductsSales;
class DashBoardController extends Controller
{
    public function __construct(){
        $this->middleware('auth:admin'); 
    }
    
    public function index(){
        $ordersCount = Orders::all()->count();
        $usersCount = User::all()->count();
        $year = date('Y');
        $month = date('n');
        $english_month = array('January','February','March','April','May','June',
            'July','August','September','October','November','December',
        );
        //get annual earnings and month earnings  
        $Earning_Annual = Earnings::where('year',$year)->get();
        if(empty($Earning_Annual[0]))
        {
            for($i = 0 ;$i <12 ;$i++){
                Earnings::create([
                    'year' => $year,
                    'month' => $i+1,
                    'earnings' => '0'
                ]);
            }
        }
        $Earning_Annual_last = Earnings::where('year',$year-1)->get();
        if(empty($Earning_Annual_last[0]))
        {
            for($i = 0 ;$i <12 ;$i++){
                Earnings::create([
                    'year' => $year-1,
                    'month' => $i+1,
                    'earnings' => '0'
                ]);
            }
        }
        $EarningsofAnnual = 0;
      
        //calcute annual earnings
        for($i = 0 ; $i < $Earning_Annual->count(); $i++){
            $EarningsofAnnual += $Earning_Annual[$i]->earnings;
        }
        $EarningsofAnnual = number_format($EarningsofAnnual);
        //calcute earnings chart data
        $count = 6;
        $earnings_labels = array();
        $earnings_data = array();
        $temp_month = $month-1;
        
        $earnings_of_current_year = $Earning_Annual;
        while($count != 0){
            if($temp_month == '-1'){
                $temp_month = 11;
                $earnings_of_current_year = $Earning_Annual_last;
            }
            array_unshift($earnings_labels,$english_month[$temp_month]);
            array_unshift($earnings_data,$earnings_of_current_year[$temp_month]->earnings);
            $temp_month--;
            $count--;
        }
        $line_data = array('labels'=>$earnings_labels,'data'=>$earnings_data);
        
        //get monthly earnings
        $Earning = Earnings::where('year',$year)->where('month',$month)->get();
        $EarningsofMonth= number_format($Earning[0]->earnings);
        
        //transfer product sales table data 
        $product_sales = ProductsSales::all();
        $sales_labels = array();
        $sales_data = array();
        foreach ($product_sales as $id => $product) {
            array_unshift($sales_labels,$product['product_name']);
            array_unshift($sales_data,$product['sales_volume']);
        }
        $Pie_data = array('labels'=>$sales_labels,'data'=>$sales_data);
        
        return view('backend.index',compact('usersCount','ordersCount','EarningsofMonth','EarningsofAnnual','line_data','Pie_data'));
    }
}

app/Http/Controllers/Backend/Share/FooterController.php
<?php

namespace App\Http\Controllers\Backend\Share;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Share\Footer;

class FooterController extends Controller
{
    public function index(){
        $footer = Footer::all()->first();
        if(empty($footer)){
            Footer::create([
                'footertext' => '© 2019 HSUN All Rights Reserved.'
            ]);
            $footer = Footer::all()->first();
        }
        return view('backend.share.footer',compact('footer'));
    }
    public function update(Request $request,$id){
        $request->validate([
            'footertext'=> ['required','string', 'max:50'],
        ]);
        $footer = Footer::find($id);
        $footer->footertext = $request->input('footertext');
        $footer->save();

        return redirect()->route('backend.share.footer.index')
                         ->with('success', 'Update successfully');
    }
}

app/Http/Controllers/Backend/User/UsersController.php
<?php

namespace App\Http\Controllers\Backend\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::paginate(6);
        return view('backend.user.users',compact('users'));
    }
}

resources/views/backend/layouts/footer.blade.php
<footer>
    <div class="footer ">
        <span>© 2019 HSUN All Rights Reserved.(Backend)</span>
    </div>
</footer>

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html lang="zh-TW">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="backend">
  <meta name="author" content="Hsun">

  <title>@yield('title')</title>

  <!-- Custom fonts for this template-->
  <link href="{{asset('bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('fontawesome/css/all.min.css')}}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet">
  
  <!-- Custom styles for this template-->
  <link href="{{ asset('css/shop_backend.css')}}" rel="stylesheet"> 

</head>

<body>
   
  <div id="wrapper">
    @include('backend.layouts.sidebar')  

    <div id="content-wrapper">

      @include('backend.layouts.navbar')  
  
      @yield('content')

      @include('backend.layouts.footer')
      
    </div>

  </div>
  <!-- Bootstrap core JavaScript -->
 
  <script src="{{asset('jquery/jquery.min.js')}}"></script> 
  <script src="{{asset('bootstrap/js/bootstrap.min.js')}}"></script>
  <script src="{{asset('fontawesome/js/all.min.js')}}"></script>
  <script src="{{asset('ckeditor/ckeditor.js')}}"></script>
  <script src="{{asset('ckeditor/adapters/jquery.js')}}"></script>
  <script src="{{asset('js/shop_backend.js')}}"></script>
  @stack('scripts')


</body>


</html>

resources/views/backend/layouts/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white shadow">
    
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <!-- Nav Item - User Information -->
      @guest                
        <a class="login" href="{{ route('login') }}"><i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>會員登入</a>
      @endguest
      @auth  

      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="">{{  Auth::user()->nickname }} </span>
          <i class="fas fa-user-astronaut fa-2x"></i>
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{{route('home')}}">
            <i class="fas fa-home fa-sm fa-fw mr-2 text-gray-400"></i>
            Home
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{ route('admin.logout') }}" 
                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
          <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
        </div>
      </li>
      @endauth  
    </ul>

  </nav>

resources/views/backend/layouts/sidebar.blade.php
<div id="sidebar" >
    
    <ul class="navbar-nav accordion" id="sidebar-content">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand" href="{{route('dashboard')}}">
            <i class="fas fa-chess-bishop fa-lg"></i><span class="sidebar-brand-text"> HSUN 後台</span>
        </a>
    
        <!-- Divider -->
        <hr>
    
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{{route('dashboard')}}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
        </li>
          
        <!-- Divider -->
        <hr>
          
        <!-- Heading -->
        <div class="sidebar-heading">
            頁面管理
        </div>
    
        <!-- Nav Item  -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-toggle="collapse" data-target="#collapse-home" aria-expanded="false" href="#" >
                <i class="fas fa-home fa-fw" aria-hidden="true"></i>
                <span>首頁</span>
            </a>
            <div class="collapse bg-white rounded collapse-box" id="collapse-home" data-parent="#sidebar-content">
                <a class="collapse-item" href="{{route('backend.home.carousel.index')}}">輪播圖</a>
                <a class="collapse-item" href="{{route('backend.home.aboutdiv.index')}}">關於區塊</a>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link collapsed" data-toggle="collapse" data-target="#collapse-about" aria-expanded="false" href="#" >
                <i class="fas fa-info-circle fa-fw" aria-hidden="true"></i>
                <span>關於我們</span>
            </a>
            <div class="collapse bg-white rounded collapse-box" id="collapse-about" data-parent="#sidebar-content">
                <a class="collapse-item" href="{{route('backend.about.introdiv.index')}}">介紹區塊</a>
                <a class="collapse-item" href="{{route('backend.about.historydiv.index')}}">沿革區塊</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('backend.news.newsdiv.index')}}" >
                <i class="far fa-newspaper fa-fw" aria-hidden="true"></i>
                <span>最新消息</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" data-toggle="collapse" data-target="#collapse-product" aria-expanded="false" href="#" >
                <i class="fas fa-coffee fa-fw" aria-hidden="true"></i>
                <span>商品介紹</span>
            </a>
            <div class="collapse bg-white rounded collapse-box" id="collapse-product" data-parent="#sidebar-content">
                <a class="collapse-item" href="{{route('backend.products.product.index')}}">商品</a>
                <a class="collapse-item" href="{{route('backend.products.menu.index')}}">菜單</a>
                <a class="collapse-item" href="{{route('backend.products.product-type.index')}}">種類</a>
            </div>
        </li>        

        <li class="nav-item">
            <a class="nav-link" href="{{route('backend.shop.shop-detail.index')}}">
            <i class="fas fa-shopping-bag fa-fw" aria-hidden="true"></i>
            <span>店鋪消息</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" data-toggle="collapse" data-target="#collapse-share" aria-expanded="false" href="#" >
                <i class="fas fa-bullhorn fa-fw" aria-hidden="true"></i>
                <span>共用內容</span>
            </a>
            <div class="collapse bg-white rounded collapse-box" id="collapse-share" data-parent="#sidebar-content">
                <a class="collapse-item" href="{{route('backend.share.shopinfo.index')}}">商品資訊</a>
                <a class="collapse-item" href="{{route('backend.share.footer.index')}}">FOOTER</a>
            </div>
        </li>
          
        <!-- Divider -->
        <hr>
          
        <!-- Heading -->
        <div class="sidebar-heading">
            使用者管理
        </div>
          
        <!-- Nav Item - Orders -->
        <li class="nav-item">
            <a class="nav-link" href="{{route('backend.user.orders.index')}}">
            <i class="fas fa-file-invoice-dollar fa-fw" aria-hidden="true"></i>
            <span>訂單資訊</span>
            </a>
        </li>
    
        <!-- Nav Item - Users -->
        <li class="nav-item">
            <a class="nav-link" href="{{route('backend.user.users.index')}}">
            <i class="fas fa-users-cog fa-fw" aria-hidden="true"></i>
            <span>使用者資料</span></a>
        </li>
    
        <!-- Divider -->
        <hr>
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    
    </ul>
</div>