routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/about', 'Frontend\AboutController@index')->name('about');
Route::get('/news', 'Frontend\NewsController@index')->name('news');
Route::get('/news/detail/{news}', 'Frontend\NewsController@show')->name('news.detail');
Route::get('/products', 'Frontend\ProductsController@index')->name('products');
Route::get('/products/detail/{product}', 'Frontend\ProductsController@show')->name('products.detail');
Route::get('/shop','Frontend\ShopController@index')->name('shop');

//cart route
Route::get('/add-to-cart/{id}', 'Frontend\CartController@getAddToCart')->name('product.addToCart');
Route::get('/cart', 'Frontend\CartController@index')->name('cart');
Route::patch('/cart/{id}', 'Frontend\CartController@updateCart')->name('cart.update');
Route::delete('/cart/{id}', 'Frontend\CartController@deleteCart')->name('cart.delete');

//order and payment route
Route::middleware(['auth'])->group(function(){
    Route::get('/order','Frontend\OrderController@index')->name('cart.order');
    Route::post('/order','Frontend\OrderController@order_confirm')->name('cart.order.confirm');
    
    Route::get('/payment','Frontend\PaymentController@index')->name('cart.payment');
    Route::post('/checkout','Frontend\PaymentController@checkout')->name('cart.checkout');

    Route::get('/orders','Frontend\User\OrdersController@index')->name('orders');
    Route::get('/order_detail/{id}','Frontend\User\OrdersController@getOrder')->name('order.detail');

    Route::get('/profile', 'Frontend\User\ProfileController@index')->name('profile');
    Route::post('/profile', 'Frontend\User\ProfileController@update')->name('profile.update');

    Route::get('/resetpassword', 'Frontend\User\ResetPasswordController@index')->name('resetpassword');
    Route::post('/resetpassword', 'Frontend\User\ResetPasswordController@update')->name('resetpassword.update');
});
Route::prefix('admin')->group(function () {
    Route::get('/', 'Auth\AdminController@showLoginForm')->name('admin.login');
    Route::post('/', 'Auth\AdminController@login')->name('admin.login');
    Route::post('/logout', 'Auth\AdminController@logout')->name('admin.logout');
});
Route::middleware(['auth:admin'])->group(function(){
    Route::get('/dashboard', 'Backend\DashBoardController@index')->name('dashboard');

    
    Route::prefix('backend')->group(function () {
        Route::group(['as' => 'backend.home.'], function() {
            Route::resource('/carousel', 'Backend\Home\CarouselController');
            Route::resource('/aboutdiv', 'Backend\Home\AboutDivController');
        });
    
        Route::group(['as' => 'backend.share.'], function() {
            Route::get('/shopinfo', 'Backend\Share\ShopInfoController@index')->name('shopinfo.index');
            Route::put('/shopinfo/{id}', 'Backend\Share\ShopInfoController@update')->name('shopinfo.update');
            Route::get('/footer', 'Backend\Share\FooterController@index')->name('footer.index');
            Route::put('/footer/{id}', 'Backend\Share\FooterController@update')->name('footer.update');
        });
    
        Route::group(['as' => 'backend.about.'], function() {
            Route::resource('/introdiv', 'Backend\About\IntroDivController');
            Route::resource('/historydiv', 'Backend\About\HistoryDivController');
        });
    
        Route::group(['as' => 'backend.news.'], function() {
            Route::resource('/newsdiv', 'Backend\News\NewsController');
        });
    
        Route::group(['as' => 'backend.products.'], function() {
            Route::resource('/menu', 'Backend\Products\MenuController');
            Route::resource('/product', 'Backend\Products\ProductController');
            Route::resource('/product-type', 'Backend\Products\ProductTypeController');
        });
    
        Route::group(['as' => 'backend.shop.'], function() {
            Route::resource('/shop-detail', 'Backend\Shop\ShopController');
        });

        Route::group(['as' => 'backend.user.'], function() {
            Route::resource('/orders', 'Backend\User\OrdersController');
            Route::get('/users', 'Backend\User\UsersController@index')->name('users.index');
        });
    });
    



});

Auth::routes();

app/Models/News/News.php
<?php

namespace App\Models\News;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = ['title','image','text'];
}

app/Http/Controllers/Backend/About/HistoryDivController.php
<?php

namespace App\Http\Controllers\Backend\About;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\About\HistoryDiv;

class HistoryDivController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $historys = HistoryDiv::paginate(5);
        return view('backend.about.historydiv.index',compact('historys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'text' =>['required','string']
        ]);

        HistoryDiv::create([
            'title'=>$request->input('title'),
            'text'=>$request->input('text'),
        ]);

        return redirect()->route('backend.about.historydiv.index')
                         ->with('success', 'New history div post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $history = HistoryDiv::find($id);
        return view('backend.about.historydiv.edit',compact('history'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'text' =>['required','string']
        ]);
        $history = HistoryDiv::find($id);
        $history->title = $request->input('title');
        $history->text = $request->input('text');
        $history->save();
        
        return redirect()->route('backend.about.historydiv.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $history = HistoryDiv::find($id);
        $history->delete();
        return redirect()->route('backend.about.historydiv.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/About/IntroDivController.php
<?php

namespace App\Http\Controllers\Backend\About;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\About\IntroDiv;
class IntroDivController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $introdivs = IntroDiv::paginate(5);
        return view('backend.about.introdiv.index',compact('introdivs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.about.introdiv.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'image'=>['required','image'],
            'text' =>['required','string']
        ],$messages = [

        ]);
     
        //if do not have introdiv directory, add it
        if (!file_exists('uploads/introdiv')) {
            mkdir('uploads/introdiv', 0755, true);
        }
        //set image path ,name and move it to local directory 
        $file = $request->file('image');

        $path = public_path() . '/uploads/introdiv/';
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $file->move($path, $fileName);

        IntroDiv::create([
            'title' =>  $request->input('title'),
            'image'=>$fileName,
            'text' => $request->input('text')
        ]);
        return redirect()->route('backend.about.introdiv.index')
                         ->with('success', 'New intro div post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $introdiv = IntroDiv::find($id);
        return view('backend.about.introdiv.detail',compact('introdiv'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $introdiv = IntroDiv::find($id);
        return view('backend.about.introdiv.edit',compact('introdiv'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'image'=>['image'],
            'text' =>['string']
        ],$messages = [
        ]);
        $introdiv = IntroDiv::find($id);
        
        if ($request->file('image')) {
            //remove original file
            @unlink('uploads/introdiv/' . $introdiv->image);

            //set image path ,name and move it to local directory
            $file = $request->file('image');
            $path = public_path() . '\uploads\introdiv\\';
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move($path, $fileName);

            $introdiv->image =  $fileName;
        }
        $introdiv->title = $request->get('title');
        $introdiv->text = $request->get('text');
        $introdiv->save();
        
        return redirect()->route('backend.about.introdiv.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $introdiv = IntroDiv::find($id);
        //remove img
        @unlink('uploads/introdiv/' . $introdiv->image);
        $introdiv->delete();
        return redirect()->route('backend.about.introdiv.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/DashBoardController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Models\Orders;
use App\Models\Earnings;
use App\Models\ProductsSales;
class DashBoardController extends Controller
{
    public function __construct(){
        $this->middleware('auth:admin'); 
    }
    
    public function index(){
        $ordersCount = Orders::all()->count();
        $usersCount = User::all()->count();
        $year = date('Y');
        $month = date('n');
        $english_month = array('January','February','March','April','May','June',
            'July','August','September','October','November','December',
        );
        //get annual earnings and month earnings  
        $Earning_Annual = Earnings::where('year',$year)->get();
        if(empty($Earning_Annual[0]))
        {
            for($i = 0 ;$i <12 ;$i++){
                Earnings::create([
                    'year' => $year,
                    'month' => $i+1,
                    'earnings' => '0'
                ]);
            }
        }
        $Earning_Annual_last = Earnings::where('year',$year-1)->get();
        if(empty($Earning_Annual_last[0]))
        {
            for($i = 0 ;$i <12 ;$i++){
                Earnings::create([
                    'year' => $year-1,
                    'month' => $i+1,
                    'earnings' => '0'
                ]);
            }
        }
        $EarningsofAnnual = 0;
      
        //calcute annual earnings
        for($i = 0 ; $i < $Earning_Annual->count(); $i++){
            $EarningsofAnnual += $Earning_Annual[$i]->earnings;
        }
        $EarningsofAnnual = number_format($EarningsofAnnual);
        //calcute earnings chart data
        $count = 6;
        $earnings_labels = array();
        $earnings_data = array();
        $temp_month = $month-1;
        
        $earnings_of_current_year = $Earning_Annual;
        while($count != 0){
            if($temp_month == '-1'){
                $temp_month = 11;
                $earnings_of_current_year = $Earning_Annual_last;
            }
            array_unshift($earnings_labels,$english_month[$temp_month]);
            array_unshift($earnings_data,$earnings_of_current_year[$temp_month]->earnings);
            $temp_month--;
            $count--;
        }
        $line_data = array('labels'=>$earnings_labels,'data'=>$earnings_data);
        
        //get monthly earnings
        $Earning = Earnings::where('year',$year)->where('month',$month)->get();
        $EarningsofMonth= number_format($Earning[0]->earnings);
        
        //transfer product sales table data 
        $product_sales = ProductsSales::all();
        $sales_labels = array();
        $sales_data = array();
        foreach ($product_sales as $id => $product) {
            array_unshift($sales_labels,$product['product_name']);
            array_unshift($sales_data,$product['sales_volume']);
        }
        $Pie_data = array('labels'=>$sales_labels,'data'=>$sales_data);
        
        return view('backend.index',compact('usersCount','ordersCount','EarningsofMonth','EarningsofAnnual','line_data','Pie_data'));
    }
}

app/Http/Controllers/Backend/Share/FooterController.php
<?php

namespace App\Http\Controllers\Backend\Share;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Share\Footer;

class FooterController extends Controller
{
    public function index(){
        $footer = Footer::all()->first();
        if(empty($footer)){
            Footer::create([
                'footertext' => '© 2019 HSUN All Rights Reserved.'
            ]);
            $footer = Footer::all()->first();
        }
        return view('backend.share.footer',compact('footer'));
    }
    public function update(Request $request,$id){
        $request->validate([
            'footertext'=> ['required','string', 'max:50'],
        ]);
        $footer = Footer::find($id);
        $footer->footertext = $request->input('footertext');
        $footer->save();

        return redirect()->route('backend.share.footer.index')
                         ->with('success', 'Update successfully');
    }
}

app/Http/Controllers/Backend/User/UsersController.php
<?php

namespace App\Http\Controllers\Backend\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::paginate(6);
        return view('backend.user.users',compact('users'));
    }
}

app/Http/Controllers/Frontend/NewsController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Share\ShopInfo;
use App\Models\Share\Calendar;
use App\Models\Share\Footer;
use App\Models\News\News;
class NewsController extends Controller
{
    public function index(){
        
        $newss = News::orderby('created_at','desc')->paginate(10);
        $shopinfo = ShopInfo::all()->first();
        $calendars = Calendar::all();
        $footer = Footer::all()->first();

        return view('frontend.news',compact('newss','shopinfo','calendars','footer'));

    }
    public function show($id)
    {
        $news = News::find($id);
        $shopinfo = ShopInfo::all()->first();
        $calendars = Calendar::all();
        $footer = Footer::all()->first();
        return view('frontend.news_detail',compact('news','shopinfo','calendars','footer'));
    }

}

resources/views/backend/news/create.blade.php
@extends('backend.layouts.master')
@section('title','NEWS-DIV | CREATE')
@section('content')
<div class="container-fluid" id="newsdiv-create">
    <div class="row title">
        <div class="col content-title">
            <i class="fas fa-plus-circle fa-2x align-middle"></i>
            <span class="align-middle">New News Post</span>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('backend.news.newsdiv.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="row ">
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Post Title</h5>
                        <p class="card-text">The title of news</p>
                        <input type="text" name="title" class="form-control" placeholder="title">
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Post Text</h5>
                        <textarea class="text" name="text" ></textarea>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        圖片上傳
                    </div>
                    <div class="card-body">
                        <input type="file" name="image" accept="image/*" class="form-control file-upload mb-3" id="image-create" >
                        <img class="preview border" src="">
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">上傳</button>
                <a href="{{route('backend.news.newsdiv.index')}}" class="btn btn-secondary">Back</a>

            </div>   
        </div>

    </form>

</div>
@endsection

resources/views/backend/news/detail.blade.php
@extends('backend.layouts.master')
@section('title','NEWS-DIV | DETAIL')
@section('content')
<div class="container-fluid" id="newsdiv-detail">
    <div class="row tb-2">
        <div class="col-md-8 ">
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Post Title:</h5>
                    <p class="card-text">{{ $news->title }}</p>
                </div>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Post Text</h5>
                    <textarea class="text" name="text" disabled>{{ $news->text }}</textarea>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-3 ">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    文章圖片
                </div>
                <div class="card-body">
                    <img class="preview border" src="{{ asset('uploads/newsdiv/' . $news->image) }}">
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <a href="{{route('backend.news.newsdiv.index')}}" class="btn btn-secondary">Back</a>
        </div>   
    </div>



</div>
@endsection

resources/views/backend/news/edit.blade.php
@extends('backend.layouts.master')
@section('title','NEWS-DIV | EDIT')
@section('content')
<div class="container-fluid" id="newsdiv-edit">

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('backend.news.newsdiv.update',$news->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row tb-2">
            <div class="col-md-8 ">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Post Title</h5>
                        <p class="card-text">The title of news</p>
                        <input type="text" name="title" class="form-control" value="{{$news->title}}" placeholder="title">
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Post Text</h5>
                        <textarea class="text" name="text">{{$news->text}}</textarea>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 ">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        圖片上傳
                    </div>
                    <div class="card-body">
                        <input type="file" name="image" accept="image/*" class="form-control file-upload mb-3" id="image-create" >
                        <img class="preview border" src="{{ asset('uploads/newsdiv/' . $news->image) }}">
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">更新</button>
                <a href="{{route('backend.news.newsdiv.index')}}" class="btn btn-secondary">Back</a>
            </div>   
        </div>

    </form>

</div>
@endsection

resources/views/backend/news/index.blade.php
@extends('backend.layouts.master')
@section('title','NEWS-DIV')
@section('content')
<div class="container-fluid" id="newsdiv">
    <div class="row title" id="news-title">
        <div class="col content-title">
            <i class="far fa-newspaper fa-3x align-middle"></i>
            <span class="align-middle">News Div</span>
            <a href="{{ route('backend.news.newsdiv.create') }}" class="btn btn-success"><i class="fas fa-plus-circle"></i> Add New</a>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
     @endif
    @if ($errors->any())
        <div id="error_msg" class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row table-content" id="newsdiv-content">
        <div class="col">
            <div class="card">
                <div class="card-header">
                        <i class="far fa-clone"></i> 新聞區塊
                </div>
                <div class="card-body tableresponsive">
                    <table class="table table-hover" >
                        <thead>
                            <tr>
                                <th>{{'#'}}</th>
                                <th>Title</th>
                                <th>Post Image</th>
                                <th>Post Text</th>
                                <th>created_at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($news as $new)   
                        <tr>
                            <td>{{ $new->id }}</td>
                            <td>{{ $new->title }}</td>
                            <td> 
                                <img src="{{ asset('uploads/newsdiv/' . $new->image) }}">
                            </td>
                            <td class="ellipsis">{{ $new->text }}</td>
                            <td>{{ $new->created_at}}</td>
                            <td>
                                {{-- View button --}}
                                <a href="{{ route('backend.news.newsdiv.show',$new->id ) }}" class="btn btn-warning"><i class="far fa-eye fa-fw"></i><span class="d-none d-lg-inline"> View</span></a>
                                {{-- edit button --}}
                                <a href="{{ route('backend.news.newsdiv.edit',$new->id ) }}" class="btn btn-primary"><i class="far fa-edit fa-fw"></i><span class="d-none d-lg-inline"> Edit</span></a>
                                {{-- delete modal button --}}
                                <button type="button" class="btn btn-danger align-top delete-button" data-toggle="modal" data-target="#deleteModal" data-id="{{ $new->id }}" data-url="{{ route('backend.news.newsdiv.destroy', $new->id ) }}" >
                                    <i class="far fa-trash-alt fa-fw"></i><span class="d-none d-lg-inline"> Delete</span>
                                </button>
                                <!-- delete Modal -->
                                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">                  
                                                <p>Are you sure you want to delete it?</p>       
                                            </div>
                                            <div class="modal-footer">
                                                <form action="{{ route('backend.news.newsdiv.destroy', $new->id ) }}" method="post"  class="d-inline delete-form">
                                                    @csrf  
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger">Yes,delete</button>
                                                </form>
                                                
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>           
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            
                        </tr>
                        @endforeach
                        </tbody>
                    </table>        
                    <div class="row pagination" >
                        <div class="col-sm-10 text-left pagination-text">
                            Showing  {{ $news->firstItem() }} to {{ $news->lastItem() }} of {{ $news->total() }} items
                        </div>
                        <div class="col-sm-2 text-left">
                            {{ $news->links() }}
                        </div>
                    </div>      
                </div>
            </div>
            
        </div>
    </div>
    
</div>
    
@endsection