routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/about', 'Frontend\AboutController@index')->name('about');
Route::get('/news', 'Frontend\NewsController@index')->name('news');
Route::get('/news/detail/{news}', 'Frontend\NewsController@show')->name('news.detail');
Route::get('/products', 'Frontend\ProductsController@index')->name('products');
Route::get('/products/detail/{product}', 'Frontend\ProductsController@show')->name('products.detail');
Route::get('/shop','Frontend\ShopController@index')->name('shop');

//cart route
Route::get('/add-to-cart/{id}', 'Frontend\CartController@getAddToCart')->name('product.addToCart');
Route::get('/cart', 'Frontend\CartController@index')->name('cart');
Route::patch('/cart/{id}', 'Frontend\CartController@updateCart')->name('cart.update');
Route::delete('/cart/{id}', 'Frontend\CartController@deleteCart')->name('cart.delete');

//order and payment route
Route::middleware(['auth'])->group(function(){
    Route::get('/order','Frontend\OrderController@index')->name('cart.order');
    Route::post('/order','Frontend\OrderController@order_confirm')->name('cart.order.confirm');
    
    Route::get('/payment','Frontend\PaymentController@index')->name('cart.payment');
    Route::post('/checkout','Frontend\PaymentController@checkout')->name('cart.checkout');

    Route::get('/orders','Frontend\User\OrdersController@index')->name('orders');
    Route::get('/order_detail/{id}','Frontend\User\OrdersController@getOrder')->name('order.detail');

    Route::get('/profile', 'Frontend\User\ProfileController@index')->name('profile');
    Route::post('/profile', 'Frontend\User\ProfileController@update')->name('profile.update');

    Route::get('/resetpassword', 'Frontend\User\ResetPasswordController@index')->name('resetpassword');
    Route::post('/resetpassword', 'Frontend\User\ResetPasswordController@update')->name('resetpassword.update');
});
Route::prefix('admin')->group(function () {
    Route::get('/', 'Auth\AdminController@showLoginForm')->name('admin.login');
    Route::post('/', 'Auth\AdminController@login')->name('admin.login');
    Route::post('/logout', 'Auth\AdminController@logout')->name('admin.logout');
});
Route::middleware(['auth:admin'])->group(function(){
    Route::get('/dashboard', 'Backend\DashBoardController@index')->name('dashboard');

    
    Route::prefix('backend')->group(function () {
        Route::group(['as' => 'backend.home.'], function() {
            Route::resource('/carousel', 'Backend\Home\CarouselController');
            Route::resource('/aboutdiv', 'Backend\Home\AboutDivController');
        });
    
        Route::group(['as' => 'backend.share.'], function() {
            Route::get('/shopinfo', 'Backend\Share\ShopInfoController@index')->name('shopinfo.index');
            Route::put('/shopinfo/{id}', 'Backend\Share\ShopInfoController@update')->name('shopinfo.update');
            Route::get('/footer', 'Backend\Share\FooterController@index')->name('footer.index');
            Route::put('/footer/{id}', 'Backend\Share\FooterController@update')->name('footer.update');
        });
    
        Route::group(['as' => 'backend.about.'], function() {
            Route::resource('/introdiv', 'Backend\About\IntroDivController');
            Route::resource('/historydiv', 'Backend\About\HistoryDivController');
        });
    
        Route::group(['as' => 'backend.news.'], function() {
            Route::resource('/newsdiv', 'Backend\News\NewsController');
        });
    
        Route::group(['as' => 'backend.products.'], function() {
            Route::resource('/menu', 'Backend\Products\MenuController');
            Route::resource('/product', 'Backend\Products\ProductController');
            Route::resource('/product-type', 'Backend\Products\ProductTypeController');
        });
    
        Route::group(['as' => 'backend.shop.'], function() {
            Route::resource('/shop-detail', 'Backend\Shop\ShopController');
        });

        Route::group(['as' => 'backend.user.'], function() {
            Route::resource('/orders', 'Backend\User\OrdersController');
            Route::get('/users', 'Backend\User\UsersController@index')->name('users.index');
        });
    });
    



});

Auth::routes();

app/Models/Home/AboutDiv.php
<?php

namespace App\Models\Home;

use Illuminate\Database\Eloquent\Model;

class AboutDiv extends Model
{
    protected $table ='aboutdiv';
    protected $fillable = ['title','image','text'];
}

app/Models/Home/Carousel.php
<?php

namespace App\Models\Home;

use Illuminate\Database\Eloquent\Model;

class Carousel extends Model
{
    protected $table ='carousel';
    protected $fillable = ['name','image_name'];
}

app/Http/Controllers/Backend/Home/AboutDivController.php
<?php

namespace App\Http\Controllers\Backend\Home;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Home\AboutDiv;
class AboutDivController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $aboutdivs = AboutDiv::paginate(5);
        
        return view('backend.home.aboutdiv.index',compact('aboutdivs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.home.aboutdiv.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'image'=>['required','image'],
            'text' =>['required','string']
        ],$messages = [

        ]);
     
        //if do not have aboutdiv directory, add it
        if (!file_exists('uploads/aboutdiv')) {
            mkdir('uploads/aboutdiv', 0755, true);
        }
        //set image path ,name and move it to local directory 
        $file = $request->file('image');

        $path = public_path() . '/uploads/aboutdiv/';
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $file->move($path, $fileName);

        AboutDiv::create([
            'title' =>  $request->input('title'),
            'image'=>$fileName,
            'text' => $request->input('text')
        ]);
        return redirect()->route('backend.home.aboutdiv.index')
                         ->with('success', 'New about div post created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $aboutdiv = AboutDiv::find($id);
        return view('backend.home.aboutdiv.detail',compact('aboutdiv'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $aboutdiv = AboutDiv::find($id);
        return view('backend.home.aboutdiv.edit',compact('aboutdiv'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $request->validate([
            'title'=> ['required','string', 'max:14'],
            'image'=>['image'],
            'text' =>['string']
        ],$messages = [
        ]);
        $aboutdiv = AboutDiv::find($id);
        
        if ($request->file('image')) {
            //remove original file
            @unlink('uploads/aboutdiv/' . $aboutdiv->image);

            //set image path ,name and move it to local directory
            $file = $request->file('image');
            $path = public_path() . '\uploads\aboutdiv\\';
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move($path, $fileName);

            $aboutdiv->image =  $fileName;
        }
        $aboutdiv->title = $request->get('title');
        $aboutdiv->text = $request->get('text');
        $aboutdiv->save();
        
        return redirect()->route('backend.home.aboutdiv.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $aboutdiv = AboutDiv::find($id);
        //remove img
        @unlink('uploads/aboutdiv/' . $aboutdiv->image);
        $aboutdiv->delete();
        return redirect()->route('backend.home.aboutdiv.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/Home/CarouselController.php
<?php

namespace App\Http\Controllers\Backend\Home;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Models\Home\Carousel;

class CarouselController extends Controller
{
    public function index(){
        $carousels = Carousel::paginate(5);

        if (empty($carousels))
            return view('backend.home.carousel.index');
        else
            return view('backend.home.carousel.index', compact('carousels'));
    }
    public function create(){
        return view('backend.home.carousel.create');
    }
    public function show($id){
        $carousel = Carousel::find($id);
        return view('backend.home.carousel.detail',compact('carousel'));
    }

    public function store(Request $request)
    { 
        //validation
        $request->validate([
            'name'=> ['required','string', 'max:14'],
            'image_name'=>['required','image']
        ],$messages = [
            'image_name.required'=>'The image field is required.',
            'image_name.image'=>'The image field must be an image.'
        ]);
     
        //if do not have carousel directory, add it
        if (!file_exists('uploads/carousel')) {
            mkdir('uploads/carousel', 0755, true);
        }
        //set image path ,name and move it to local directory 
        $file = $request->file('image_name');

        $path = public_path() . '/uploads/carousel/';
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $file->move($path, $fileName);

        Carousel::create([
            'name' =>  $request->input('name'),
            'image_name'=>$fileName
        ]);
        return redirect()->route('backend.home.carousel.index')
                         ->with('success', 'New carousel img created successfully');
                    
    }
    public function edit($id){
        $carousel = Carousel::find($id);
        return view('backend.home.carousel.edit',compact('carousel'));
    }

    public function update(Request $request,$id){

        //validation
        $request->validate([
            'name'=> ['required','string', 'max:14'],
            'image_name'=>['mimes:,image','max:1000']
        ]);
        $carousel = Carousel::find($id);
        
        if ($request->file('image_name')) {
            //remove original file
            @unlink('uploads/carousel/' . $carousel->image_name);

            //set image path ,name and move it to local directory
            $file = $request->file('image_name');
            $path = public_path() . '\uploads\carousel\\';
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move($path, $fileName);

            $carousel->image_name =  $fileName;
        }
        $carousel->name = $request->get('name');
        $carousel->save();
        
        return redirect()->route('backend.home.carousel.index')
                         ->with('success', 'Update successfully');
    }

    public function destroy($id){
        $carousel = Carousel::find($id);
        //remove img
        @unlink('uploads/carousel/' . $carousel->image_name);
        $carousel->delete();
        return redirect()->route('backend.home.carousel.index')
                         ->with('success', 'Delete successfully');
    }
    
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Home\Carousel;
use App\Models\Home\AboutDiv;
use App\Models\Share\ShopInfo;
use App\Models\Share\Calendar;
use App\Models\Share\Footer;
use App\Models\News\News;
class HomeController extends Controller
{
    public function index(){
        
        $carousels = Carousel::all();
        $aboutdivs = AboutDiv::all();
        $newss = News::orderby('created_at','desc')->take(5)->get();
        $shopinfo = ShopInfo::all()->first();
        $calendars = Calendar::all();
        $footer = Footer::all()->first();
        
        return view('frontend.index',compact('carousels','aboutdivs','newss','shopinfo','calendars','footer'));

    }
}

resources/views/backend/home/carousel/create.blade.php
@extends('backend.layouts.master')
@section('title','Carousel | CREATE')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h3>New Carousel Image</h3>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('backend.home.carousel.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="row ">
            <div class="col-md-12 mb-3">
                <strong>圖片名稱 :</strong>
                <input type="text" name="name" class="form-control" placeholder="Image Name">
            </div>
            <div class="col-md-12 mb-3">
                <strong>上傳圖片 :</strong>
                <input type="file" name="image_name" class="form-control file-upload" >
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-sm btn-primary">Submit</button>
                <a href="{{route('backend.home.carousel.index')}}" class="btn btn-sm btn-success">Back</a>
                
            </div>
        </div>
    </form>

</div>
@endsection

resources/views/backend/home/carousel/detail.blade.php
@extends('backend.layouts.master')
@section('title','Carousel | DETAIL')
@section('content')
    <div class="container-fluid" id="carousel-detail">
        <div class="row tb-2">
            
            <div class="col-md-12">
                <div class="form-group">
                    <h5>Name:</h5> 
                    {{$carousel->name}}
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <h5>Image:</h5>
                    <img src="{{ asset('uploads/carousel/' . $carousel->image_name) }}">
                </div>
            </div>
            <div class="col-md-12">
                <a href="{{route('backend.home.carousel.index')}}" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>

@endsection

resources/views/backend/home/carousel/edit.blade.php
@extends('backend.layouts.master')
@section('title','Carousel | EDIT')
@section('content')
    <div class="container-fluid" id="carousel-edit">
        <div class="row tb-2">
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <form action="{{route('backend.home.carousel.update',$carousel->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <h5>Name:</h5> 
                        <input type="text" name="name" class="form-control" placeholder="Image Name" value="{{$carousel->name}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <h5>Image:</h5>
                        <input type="file" name="image_name" accept="image/*" class="form-control file-upload" id="img-update">
                    </div>     
                </div>
                <div class="col-md-12">
                    <img class="preview"src="{{ asset('uploads/carousel/' . $carousel->image_name) }}">
                </div>
            </div>
            <div class="row tb-2">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">更新</button>
                    <a href="{{route('backend.home.carousel.index')}}" class="btn btn-secondary">Back</a>
                </div>       
            </div>
        </form>
    </div>

@endsection

resources/views/backend/home/carousel/index.blade.php
@extends('backend.layouts.master')
@section('title','Carousel')
@section('content')
<div class="container-fluid" id="carousel">
    <div class="row title" id="carousel-title">
        <div class="col content-title">
            <i class="fas fa-images fa-3x align-middle"></i>
            <span class="align-middle">Carousel</span>
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#createModal">
                <i class="fas fa-plus-circle"></i> Add New
            </button>
            
            <!-- create new Modal -->
            <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="createModalLabel">Add New</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">                  
                            <form action="{{route('backend.home.carousel.store')}}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row ">
                                    <div class="col-md-12 mb-3">
                                        <strong>圖片名稱 :</strong>
                                        <input type="text" name="name" class="form-control" placeholder="Image Name">
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <strong>上傳圖片 :</strong>
                                        <input type="file" name="image_name" accept="image/*" class="form-control file-upload" >
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">上傳</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>           
                                </div>
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
     @endif
    @if ($errors->any())
        <div id="error_msg" class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row table-content" id="carousel-content">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <i class="far fa-caret-square-right"></i> 輪播圖
                </div>
                <div class="card-body tableresponsive">
                    <table class="table table-hover" >
                        <thead>
                            <tr>
                                <th>{{'#'}}</th>
                                <th>Name</th>
                                <th>Post Image</th>
                                <th>created_at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($carousels as $carousel)                            
                            <tr>
                                <td id="carousel-id">{{ $carousel->id }}</td>
                                <td>{{ $carousel->name }}</td>
                                <td>
                                    <img src="{{ asset('uploads/carousel/' . $carousel->image_name) }}">
                                </td>
                                <td>{{ $carousel->created_at }} </td>
                                <td>
                                    {{-- View button --}}
                                    <a href="{{ route('backend.home.carousel.show',$carousel->id ) }}" class="btn btn-warning"><i class="far fa-eye fa-fw"></i><span class="d-none d-lg-inline"> View</span></a>
                                    {{-- edit button --}}
                                    <a href="{{ route('backend.home.carousel.edit',$carousel->id ) }}" class="btn btn-primary"><i class="far fa-edit fa-fw"></i><span class="d-none d-lg-inline"> Edit</span></a>
                                    {{-- delete modal button --}}
                                    <button type="button" class="btn btn-danger align-top delete-button" data-toggle="modal" data-target="#deleteModal" data-id="{{ $carousel->id }}" data-url="{{ route('backend.home.carousel.destroy', $carousel->id ) }}" >
                                        <i class="far fa-trash-alt fa-fw"></i><span class="d-none d-lg-inline"> Delete</span>
                                    </button>
                                 </td>
                                 <!-- delete Modal -->
                                 <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                     <div class="modal-dialog" role="document">
                                         <div class="modal-content">
                                             <div class="modal-header">
                                                 <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                                                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                     <span aria-hidden="true">&times;</span>
                                                 </button>
                                             </div>
                                             <div class="modal-body">                  
                                                 <p>Are you sure you want to delete it?</p>       
                                             </div>
                                             <div class="modal-footer">
                                                 <form action="{{ route('backend.home.carousel.destroy', $carousel->id ) }}" method="post"  class="d-inline delete-form">
                                                     @csrf  
                                                     @method('DELETE')
                                                     <button type="submit" class="btn btn-danger">Yes,delete</button>
                                                 </form>
                                                 
                                                 <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>           
                                             </div>
                                         </div>
                                     </div>
                                 </div>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    
                    <div class="row pagination" >
                        <div class="col-sm-10 text-left pagination-text">
                            Showing  {{ $carousels->firstItem() }} to {{ $carousels->lastItem() }} of {{ $carousels->total() }} items
                        </div>
                        <div class="col-sm-2 text-left">
                            {{ $carousels->links() }}
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    
</div>
@endsection