routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\HomeController@index')->name('home');
Route::get('/about', 'Frontend\AboutController@index')->name('about');
Route::get('/news', 'Frontend\NewsController@index')->name('news');
Route::get('/news/detail/{news}', 'Frontend\NewsController@show')->name('news.detail');
Route::get('/products', 'Frontend\ProductsController@index')->name('products');
Route::get('/products/detail/{product}', 'Frontend\ProductsController@show')->name('products.detail');
Route::get('/shop','Frontend\ShopController@index')->name('shop');

//cart route
Route::get('/add-to-cart/{id}', 'Frontend\CartController@getAddToCart')->name('product.addToCart');
Route::get('/cart', 'Frontend\CartController@index')->name('cart');
Route::patch('/cart/{id}', 'Frontend\CartController@updateCart')->name('cart.update');
Route::delete('/cart/{id}', 'Frontend\CartController@deleteCart')->name('cart.delete');

//order and payment route
Route::middleware(['auth'])->group(function(){
    Route::get('/order','Frontend\OrderController@index')->name('cart.order');
    Route::post('/order','Frontend\OrderController@order_confirm')->name('cart.order.confirm');
    
    Route::get('/payment','Frontend\PaymentController@index')->name('cart.payment');
    Route::post('/checkout','Frontend\PaymentController@checkout')->name('cart.checkout');

    Route::get('/orders','Frontend\User\OrdersController@index')->name('orders');
    Route::get('/order_detail/{id}','Frontend\User\OrdersController@getOrder')->name('order.detail');

    Route::get('/profile', 'Frontend\User\ProfileController@index')->name('profile');
    Route::post('/profile', 'Frontend\User\ProfileController@update')->name('profile.update');

    Route::get('/resetpassword', 'Frontend\User\ResetPasswordController@index')->name('resetpassword');
    Route::post('/resetpassword', 'Frontend\User\ResetPasswordController@update')->name('resetpassword.update');
});
Route::prefix('admin')->group(function () {
    Route::get('/', 'Auth\AdminController@showLoginForm')->name('admin.login');
    Route::post('/', 'Auth\AdminController@login')->name('admin.login');
    Route::post('/logout', 'Auth\AdminController@logout')->name('admin.logout');
});
Route::middleware(['auth:admin'])->group(function(){
    Route::get('/dashboard', 'Backend\DashBoardController@index')->name('dashboard');

    
    Route::prefix('backend')->group(function () {
        Route::group(['as' => 'backend.home.'], function() {
            Route::resource('/carousel', 'Backend\Home\CarouselController');
            Route::resource('/aboutdiv', 'Backend\Home\AboutDivController');
        });
    
        Route::group(['as' => 'backend.share.'], function() {
            Route::get('/shopinfo', 'Backend\Share\ShopInfoController@index')->name('shopinfo.index');
            Route::put('/shopinfo/{id}', 'Backend\Share\ShopInfoController@update')->name('shopinfo.update');
            Route::get('/footer', 'Backend\Share\FooterController@index')->name('footer.index');
            Route::put('/footer/{id}', 'Backend\Share\FooterController@update')->name('footer.update');
        });
    
        Route::group(['as' => 'backend.about.'], function() {
            Route::resource('/introdiv', 'Backend\About\IntroDivController');
            Route::resource('/historydiv', 'Backend\About\HistoryDivController');
        });
    
        Route::group(['as' => 'backend.news.'], function() {
            Route::resource('/newsdiv', 'Backend\News\NewsController');
        });
    
        Route::group(['as' => 'backend.products.'], function() {
            Route::resource('/menu', 'Backend\Products\MenuController');
            Route::resource('/product', 'Backend\Products\ProductController');
            Route::resource('/product-type', 'Backend\Products\ProductTypeController');
        });
    
        Route::group(['as' => 'backend.shop.'], function() {
            Route::resource('/shop-detail', 'Backend\Shop\ShopController');
        });

        Route::group(['as' => 'backend.user.'], function() {
            Route::resource('/orders', 'Backend\User\OrdersController');
            Route::get('/users', 'Backend\User\UsersController@index')->name('users.index');
        });
    });
    



});

Auth::routes();

app/Http/Controllers/Backend/Products/MenuController.php
<?php

namespace App\Http\Controllers\Backend\Products;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Products\Menu;
use App\Models\Products\ProductType;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::orderby('type')->paginate(5);
        return view('backend.products.menu.index',compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = ProductType::where('type','Menu')->get();
        return view('backend.products.menu.create',compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'name'=> ['required','string'],
            'image'=>['required','image'],
            'price' =>['required','integer'],
            'description' =>['required','string'],
            'type' =>['required','string']
        ]);
     
        //if do not have menu directory, add it
        if (!file_exists('uploads/menu')) {
            mkdir('uploads/menu', 0755, true);
        }
        //set image path ,name and move it to local directory 
        $file = $request->file('image');

        $path = public_path() . '/uploads/menu/';
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $file->move($path, $fileName);
        Menu::create([
            'name' =>  $request->input('name'),
            'image'=>$fileName,
            'price' => $request->input('price'),
            'type' => $request->input('type'),
            'description' => $request->input('description')
        ]);
        return redirect()->route('backend.products.menu.index')
                         ->with('success', 'New product created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $menu = Menu::find($id);
        return view('backend.products.menu.detail',compact('menu'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $types = ProductType::where('type','Menu')->get();
        $menu = Menu::find($id);
        return view('backend.products.menu.edit',compact('types','menu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $request->validate([
            'name'=> ['string'],
            'image'=>['image'],
            'price' =>['integer'],
            'description' =>['string'],
            'type' =>['required','string']
        ]);
        $menu = Menu::find($id);
        
        if ($request->file('image')) {
            //remove original file
            @unlink('uploads/menu/' . $menu->image);

            //set image path ,name and move it to local directory
            $file = $request->file('image');
            $path = public_path() . '\uploads\menu\\';
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move($path, $fileName);

            $menu->image =  $fileName;
        }
        $menu->name = $request->input('name');
        $menu->price = $request->input('price');
        $menu->type = $request->input('type');
        $menu->description = $request->input('description');
      
        $menu->save();
        
        return redirect()->route('backend.products.menu.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $menu = Menu::find($id);
        //remove img
        @unlink('uploads/menu/' . $menu->image);
        $menu->delete();
        return redirect()->route('backend.products.menu.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/Products/ProductController.php
<?php

namespace App\Http\Controllers\Backend\Products;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Products\Product;
use App\Models\Products\ProductType;
use App\Models\ProductsSales;
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderby('type')->paginate(5);
        return view('backend.products.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = ProductType::where('type','Product')->get();
        return view('backend.products.product.create',compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'name'=> ['required','string'],
            'image'=>['required','image'],
            'price' =>['required','integer'],
            'description' =>['required','string'],
            'type' =>['required','string']
        ]);
     
        //if do not have product directory, add it
        if (!file_exists('uploads/product')) {
            mkdir('uploads/product', 0755, true);
        }
        //set image path ,name and move it to local directory 
        $file = $request->file('image');

        $path = public_path() . '/uploads/product/';
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $file->move($path, $fileName);
        Product::create([
            'name' =>  $request->input('name'),
            'image'=>$fileName,
            'price' => $request->input('price'),
            'type' => $request->input('type'),
            'description' => $request->input('description')
        ]);
        //product sales table create
        ProductsSales::create([
            'product_name' =>  $request->input('name'),
            'sales_volume'=> '0'
        ]);
        return redirect()->route('backend.products.product.index')
                         ->with('success', 'New product created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('backend.products.product.detail',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $types = ProductType::where('type','Product')->get();
        $product = Product::find($id);
        return view('backend.products.product.edit',compact('types','product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $request->validate([
            'name'=> ['string'],
            'image'=>['image'],
            'price' =>['integer'],
            'description' =>['string'],
            'type' =>['required','string']
        ]);
        $product = Product::find($id);
        
        if ($request->file('image')) {
            //remove original file
            @unlink('uploads/product/' . $product->image);

            //set image path ,name and move it to local directory
            $file = $request->file('image');
            $path = public_path() . '\uploads\product\\';
            $fileName = time() . '.' . $file->getClientOriginalExtension();
            $file->move($path, $fileName);

            $product->image =  $fileName;
        }
        $old_name = $product->name;
        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $product->type = $request->input('type');
        $product->description = $request->input('description');
        $product->save();

        //product sales table update
        $product_sales = ProductsSales::where('product_name',$old_name)->get();
        $product_sales[0]->product_name = $request->input('name');
        $product_sales[0]->save();

        return redirect()->route('backend.products.product.index')
                         ->with('success', 'Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        //remove img
        @unlink('uploads/product/' . $product->image);
        $product->delete();
        $product_sales = ProductsSales::where('product_name',$product->name)->get();
        $product_sales[0]->delete();
        return redirect()->route('backend.products.product.index')
                         ->with('success', 'Delete successfully');
    }
}

app/Http/Controllers/Backend/Products/ProductTypeController.php
<?php

namespace App\Http\Controllers\Backend\Products;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Products\ProductType;

class ProductTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = ProductType::orderby('type','order')->paginate(5);
        return view('backend.products.product_type.index',compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>['required','string','max:20'],  
            'type'=>['required','string','max:20'],  
            'order'=>['required','integer']   
        ]);
        ProductType::create([
            'name'=>$request->input('name'),
            'type'=>$request->input('type'),
            'order'=>$request->input('order')
        ]);

        return redirect()->route('backend.products.product-type.index')
                         ->with('success','New product type created successfully');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $type = ProductType::find($id);
        $types = ProductType::all();
        return view('backend.products.product_type.edit',compact('types','type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>['required','string','max:20'],  
            'type'=>['required','string','max:20'],  
            'order'=>['required','integer']  
        ]);
        
        $product_type = ProductType::find($id);
        $product_type->name = $request->input('name');
        $product_type->type = $request->input('type');
        $product_type->order = $request->input('order');
        $product_type->save();

        return redirect()->route('backend.products.product-type.index')
                         ->with('success','Update successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product_type = ProductType::find($id);
        $product_type->delete();
        return redirect()->route('backend.products.product-type.index')
                         ->with('success', 'Delete successfully');
    }
}

resources/views/backend/products/product/create.blade.php
@extends('backend.layouts.master')
@section('title','PRODUCT | CREATE')
@section('content')
<div class="container-fluid" id="product-create">
    <div class="row title">
        <div class="col content-title">
            <i class="fas fa-plus-circle fa-2x align-middle"></i>
            <span class="align-middle">New Product</span>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('backend.products.product.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="row ">
            <div class="col-md-7">
                <div class="card mb-3">
                    <div class="card-header bg-warning">Product Info:</div>
                    <div class="card-body">
                        <span >Product Name:</span>
                        <input type="text" name="name" class="form-control" placeholder="name">
                        <span >Product Type:</span>
                        <select class="form-control" name="type" >
                            @foreach ($types as $type)
                                <option>{{$type->name}}</option>
                            @endforeach
                        </select>
                        <span >Product Price:</span>
                        <input type="text" name="price" class="form-control" placeholder="price">
                    </div>
                </div>       
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Product description</h5>
                        <textarea name="description" id="description"></textarea>
                    </div>
                </div>
            </div>
            <div class="col-md-5 mb-3 ">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        圖片上傳
                    </div>
                    <div class="card-body">
                        <input type="file" name="image" accept="image/*" class="form-control file-upload mb-3" id="image-create" >
                        <img class="preview border" src="">
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">上傳</button>
                <a href="{{route('backend.products.product.index')}}" class="btn btn-secondary">Back</a>

            </div>   
        </div>

    </form>

</div>
@endsection

resources/views/backend/products/product/detail.blade.php
@extends('backend.layouts.master')
@section('title','PRODUCT | DETAIL')
@section('content')
<div class="container-fluid" id="product-detail">
    <div class="row tb-2">
        <div class="col-md-8 ">
            <div class="card mb-3">
                <div class="card-header bg-warning">Product Info:</div>
                <div class="card-body">
                    <h5>Name:</h5>
                    <p>{{$product->name}}</p>
                    <h5 >Type:</h5>
                    <p>{{$product->type}}</p>
                    <h5 >Price:</h5>
                    <p>{{$product->price}}</p>
                </div>
            </div>      
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Product description</h5>
                    <textarea name="description" id="description" disabled>{{$product->description}}</textarea>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-3 ">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    文章圖片
                </div>
                <div class="card-body">
                    <img class="preview border" src="{{ asset('uploads/product/' . $product->image) }}">
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <a href="{{route('backend.products.product.index')}}" class="btn btn-secondary">Back</a>
        </div>   
    </div>



</div>
@endsection

resources/views/backend/products/product/edit.blade.php
@extends('backend.layouts.master')
@section('title','PRODUCT | EDIT')
@section('content')
<div class="container-fluid" id="product-edit">

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{route('backend.products.product.update',$product->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row tb-2">
            <div class="col-md-8 ">
                <div class="card mb-3">
                    <div class="card-header bg-warning">Product Info:</div>
                    <div class="card-body">
                        <span >Product Name:</span>
                        <input type="text" name="name" class="form-control" value="{{$product->name}}" placeholder="name">
                        <span >Product Type:</span>
                        <select class="form-control" name="type" >
                            @foreach ($types as $type)
                                @if ($type->name == $product->type)
                                    <option selected>{{$type->name}}</option>
                                @else
                                    <option>{{$type->name}}</option>
                                @endif
                            @endforeach
                        </select>
                        <span >Product Price:</span>
                        <input type="text" name="price" class="form-control" value="{{$product->price}}" placeholder="price">
                    </div>
                </div>       
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Post Text</h5>
                        <textarea id="description" name="description">{{$product->description}}</textarea>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 ">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        圖片上傳
                    </div>
                    <div class="card-body">
                        <input type="file" name="image" accept="image/*" class="form-control file-upload mb-3" id="image-create" >
                        <img class="preview border" src="{{ asset('uploads/product/' . $product->image) }}">
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">更新</button>
                <a href="{{route('backend.products.product.index')}}" class="btn btn-secondary">Back</a>
            </div>   
        </div>

    </form>

</div>
@endsection

resources/views/backend/products/product/index.blade.php
@extends('backend.layouts.master')
@section('title','PRODUCTS | PRODUCT')
@section('content')
<div class="container-fluid" id="product">
    <div class="row title" id="menu-title">
        <div class="col content-title">
            <i class="fas fa-store fa-3x align-middle"></i>
            <span class="align-middle">Product</span>
            <a href="{{ route('backend.products.product.create') }}" class="btn btn-success"><i class="fas fa-plus-circle"></i> Add New</a>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
     @endif
    @if ($errors->any())
        <div id="error_msg" class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row table-content" id="product-content">
        <div class="col">
            <div class="card">
                <div class="card-header">
                        <i class="far fa-clone"></i> 商品
                </div>
                <div class="card-body tableresponsive">
                    <table class="table table-hover" >
                        <thead>
                            <tr>
                                <th>{{'#'}}</th>
                                <th>name</th>
                                <th>Product Image</th>
                                <th>description</th>
                                <th>Price</th>
                                <th>type</th>
                                <th>created_at</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($products as $product)   
                        <tr>
                            <td>{{ $product->id }}</td>
                            <td>{{ $product->name }}</td>
                            <td> 
                                <img src="{{ asset('uploads/product/' . $product->image) }}">
                            </td>
                            <td class="ellipsis">{{ $product->description }}</td>
                            <td >${{ $product->price }}</td>
                            <td >{{ $product->type }}</td>
                            <td>{{ $product->created_at}}</td>
                            <td>
                                {{-- View button --}}
                                <a href="{{ route('backend.products.product.show',$product->id ) }}" class="btn btn-warning"><i class="far fa-eye fa-fw"></i><span class="d-none d-lg-inline"> View</span></a>
                                {{-- edit button --}}
                                <a href="{{ route('backend.products.product.edit',$product->id ) }}" class="btn btn-primary"><i class="far fa-edit fa-fw"></i><span class="d-none d-lg-inline"> Edit</span></a>
                                {{-- delete modal button --}}
                                <button type="button" class="btn btn-danger align-top delete-button" data-toggle="modal" data-target="#deleteModal" data-id="{{ $product->id }}" data-url="{{ route('backend.products.product.destroy', $product->id ) }}" >
                                    <i class="far fa-trash-alt fa-fw"></i><span class="d-none d-lg-inline"> Delete</span>
                                </button>
                                <!-- delete Modal -->
                                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">                  
                                                <p>Are you sure you want to delete it?</p>       
                                            </div>
                                            <div class="modal-footer">
                                                <form action="{{ route('backend.products.product.destroy', $product->id ) }}" method="post"  class="d-inline delete-form">
                                                    @csrf  
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger">Yes,delete</button>
                                                </form>
                                                
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>           
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            
                        </tr>
                        @endforeach
                        </tbody>
                    </table>        
                    <div class="row pagination" >
                        <div class="col-sm-10 text-left pagination-text">
                            Showing  {{ $products->firstItem() }} to {{ $products->lastItem() }} of {{ $products->total() }} items
                        </div>
                        <div class="col-sm-2 text-left">
                            {{ $products->links() }}
                        </div>
                    </div>      
                </div>
            </div>
            
        </div>
    </div>
    
</div>
    
@endsection